import DefaultLayout from '@/components/appLayouts/defaultLayout';
import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="flex justify-center bg-[url('../public/assets/images/what-the-hex.webp')]">
                <DefaultLayout children={children} />
            </body>
        </html>
    );
}
